In [1]:
#!pip install scikit-learn
#!pip install --upgrade numpy pandas
#!pip install numpy==1.21 pandas==1.3
!pip install --force-reinstall numpy pandas
!pip install numpy==1.21 pandas==1.3

  Using cached numpy-2.0.2-cp39-cp39-macosx_10_9_x86_64.whl (21.2 MB)
  Using cached pandas-2.2.3-cp39-cp39-macosx_10_9_x86_64.whl (12.6 MB)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
  Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
  Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
  Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
  Attempting uninstall: pytz
    Found existing installation: pytz 2024.2
    Uninstalling pytz-2024.2:
      Successfully uninstalled pytz-2024.2
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2024.2
    Uninstalling tzdata-2024.2:
      Successfully uninstalled tzdata-2024.2
  Attempting uninstall: six
    Found existing installation: six 1.17.0
    Uninstalling six-1.17.0:
      Successfully uninstalled six-1.17.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.0
    Uninstalling numpy-1.21.0:
      Successfully uninstalled numpy-1.21.0
  Attempting uninst

In [2]:
# Verify Installed Versions
import numpy as np
import pandas as pd

print("Numpy version:", np.__version__)
print("Pandas version:", pd.__version__)

Numpy version: 1.21.0
Pandas version: 1.3.0


In [3]:
# importing libs
import os
import pandas as pd

# machine learning libs
from sklearn.linear_model import LogisticRegression

/Users/dellacorte/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/__init__.py:21: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 1.21.0)
  from scipy.sparse import issparse


In [4]:
# Get the current working directory
current_directory = os.getcwd()
print("Current Directory:", current_directory)

Current Directory: /Users/dellacorte/py-projects/data-science/supervised-learning-classification-pipeline


In [5]:
# Read the dataset
df_abt = pd.read_csv('/Users/dellacorte/py-projects/data-science/supervised-learning-classification-pipeline/databases/propensao_revenda_abt.csv')
df_abt.head() 

data_ref_safra                         seller_id  uf  tot_orders_12m  \
0     2018-01-01  0015a82c2db000af6aaaf3ae2ecb0532  SP               3   
1     2018-01-01  001cca7ae9ae17fb1caed9dfb1094831  ES             171   
2     2018-01-01  002100f778ceb8431b7a1020ff7ab48f  SP              38   
3     2018-01-01  003554e2dce176b5555353e4f3555ac8  GO               1   
4     2018-01-01  004c9cd9d87a3c30c522c48c4fc07416  SP             130   

   tot_items_12m  tot_items_dist_12m  receita_12m  recencia  \
0              3                   1      2685.00        74   
1            207                   9     21275.23         2   
2             42                  15       781.80         2   
3              1                   1       120.00        16   
4            141                  75     16228.88         8   

   nao_revendeu_next_6m  
0                     1  
1                     0  
2                     0  
3                     1  
4                     0

In [6]:
# key variables
key_vars = ['data_ref_safra', 'seller_id']

# numeric variables
num_vars = ['tot_orders_12m', 'tot_items_12m', 'tot_items_dist_12m', 'receita_12m', 'recencia']

# categorical variables
cat_vars = ['uf']

# target
target = 'nao_revendeu_next_6m'

# creating our dataframe with the variables listed
# excluding key variables, as they are not important
features = cat_vars + num_vars

# creating a dataframe with variables
X = df_abt[features]
X.head()

uf  tot_orders_12m  tot_items_12m  tot_items_dist_12m  receita_12m  \
0  SP               3              3                   1      2685.00   
1  ES             171            207                   9     21275.23   
2  SP              38             42                  15       781.80   
3  GO               1              1                   1       120.00   
4  SP             130            141                  75     16228.88   

   recencia  
0        74  
1         2  
2         2  
3        16  
4         8

In [7]:
# creating a dataframe with target variable
y = df_abt[target]
y.head()

0    1
1    0
2    0
3    1
4    0
Name: nao_revendeu_next_6m, dtype: int64

In [9]:
# creating a variable with the logistic regression model
lr_model = LogisticRegression(random_state=42)

# making the model parameters (X, y) available
lr_model.fit(X=X[num_vars], y=y)

/Users/dellacorte/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=42)

In [13]:
# interceptor
lr_model.intercept_

array([-1.48739767])

In [14]:
# coefficient
lr_model.coef_

array([[-1.05500593e-02,  6.67061909e-03, -4.34068580e-02,
        -4.50547976e-05,  2.20512256e-02]])

In [15]:
# model prediction
y_pred = lr_model.predict(X[num_vars])
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
# passing the features manually into the model
lr_model.predict([[3, 3, 1, 2685.0, 74]])

/Users/dellacorte/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [18]:
# dataframe with expected target and predicted target
df_res = pd.DataFrame()

df_res['y_expected'] = y.copy()
df_res['y_predicted'] = y_pred.copy()

df_res

y_expected  y_predicted
0              1            0
1              0            0
2              0            0
3              1            0
4              0            0
...          ...          ...
5364           1            0
5365           0            0
5366           0            0
5367           0            0
5368           0            0

[5369 rows x 2 columns]

In [19]:
# concatenating my expected/predicted dataframe with my features
df_res = pd.concat([df_abt, df_res], axis=1)

df_res

data_ref_safra                         seller_id  uf  tot_orders_12m  \
0        2018-01-01  0015a82c2db000af6aaaf3ae2ecb0532  SP               3   
1        2018-01-01  001cca7ae9ae17fb1caed9dfb1094831  ES             171   
2        2018-01-01  002100f778ceb8431b7a1020ff7ab48f  SP              38   
3        2018-01-01  003554e2dce176b5555353e4f3555ac8  GO               1   
4        2018-01-01  004c9cd9d87a3c30c522c48c4fc07416  SP             130   
...             ...                               ...  ..             ...   
5364     2018-03-01  ff82e8873fba613f2261a9acc896fd84  MG               4   
5365     2018-03-01  ffc470761de7d0232558ba5e786e57b7  SP               5   
5366     2018-03-01  ffdd9f82b9a447f6f8d4b91554cc7dd3  PR              11   
5367     2018-03-01  ffeee66ac5d5a62fe688b9d26f83f534  SP              13   
5368     2018-03-01  fffd5413c0700ac820c7069d66d98c89  SP              33   

      tot_items_12m  tot_items_dist_12m  receita_12m  recencia  \
0                 3                   1      2685.00        74   
1               207                   9     21275.23         2   
2                42                  15       781.80         2   
3                 1                   1       120.00        16   
4               141                  75     16228.88         8   
...             ...                 ...          ...       ...   
5364              4                   3       124.60        12   
5365              5                   5       385.59         0   
5366             12                   8      1450.20         7   
5367             13                   3      1709.87         0   
5368             34                  22      5488.60        14   

      nao_revendeu_next_6m  y_expected  y_predicted  
0                        1           1            0  
1                        0           0            0  
2                        0           0            0  
3                        1           1            0  
4                        0           0            0  
...                    ...         ...          ...  
5364                     1           1            0  
5365                     0           0            0  
5366                     0           0            0  
5367                     0           0            0  
5368                     0           0            0  

[5369 rows x 11 columns]